
/////${NFC_HOME}/lib/verilog-axi/rtl/arbiter.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_adapter_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_adapter.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_adapter_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_axil_adapter_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_axil_adapter.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_axil_adapter_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_cdma_desc_mux.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_cdma.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_crossbar_addr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_crossbar_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_crossbar.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_crossbar_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_dma_desc_mux.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_dma_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_dma.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_dma_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_dp_ram.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_fifo_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_fifo.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_fifo_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_interconnect.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_adapter_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_adapter.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_adapter_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_cdc_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_cdc.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_cdc_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_dp_ram.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_interconnect.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_ram.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_register_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_register.v
${NFC_HOME}/lib/verilog-axi/rtl/axil_register_wr.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_ram_rd_if.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_ram.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_ram_wr_if.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_ram_wr_rd_if.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_register_rd.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_register.v
${NFC_HOME}/lib/verilog-axi/rtl/axi_register_wr.v
////${NFC_HOME}/lib/verilog-axi/rtl/priority_encoder.v

${NFC_HOME}/lib/axis/rtl/arbiter.v
${NFC_HOME}/lib/axis/rtl/axis_adapter.v
${NFC_HOME}/lib/axis/rtl/axis_arb_mux.v
${NFC_HOME}/lib/axis/rtl/axis_async_fifo_adapter.v
${NFC_HOME}/lib/axis/rtl/axis_async_fifo.v
${NFC_HOME}/lib/axis/rtl/axis_broadcast.v
${NFC_HOME}/lib/axis/rtl/axis_cobs_decode.v
${NFC_HOME}/lib/axis/rtl/axis_cobs_encode.v
${NFC_HOME}/lib/axis/rtl/axis_crosspoint.v
${NFC_HOME}/lib/axis/rtl/axis_demux.v
${NFC_HOME}/lib/axis/rtl/axis_fifo_adapter.v
${NFC_HOME}/lib/axis/rtl/axis_fifo.v
${NFC_HOME}/lib/axis/rtl/axis_frame_join.v
${NFC_HOME}/lib/axis/rtl/axis_frame_length_adjust_fifo.v
${NFC_HOME}/lib/axis/rtl/axis_frame_length_adjust.v
${NFC_HOME}/lib/axis/rtl/axis_frame_len.v
${NFC_HOME}/lib/axis/rtl/axis_ll_bridge.v
${NFC_HOME}/lib/axis/rtl/axis_mux.v
${NFC_HOME}/lib/axis/rtl/axis_pipeline_register.v
${NFC_HOME}/lib/axis/rtl/axis_ram_switch.v
${NFC_HOME}/lib/axis/rtl/axis_rate_limit.v
${NFC_HOME}/lib/axis/rtl/axis_register.v
${NFC_HOME}/lib/axis/rtl/axis_srl_fifo.v
${NFC_HOME}/lib/axis/rtl/axis_srl_register.v
${NFC_HOME}/lib/axis/rtl/axis_stat_counter.v
${NFC_HOME}/lib/axis/rtl/axis_switch.v
${NFC_HOME}/lib/axis/rtl/axis_tap.v
${NFC_HOME}/lib/axis/rtl/ll_axis_bridge.v
${NFC_HOME}/lib/axis/rtl/priority_encoder.v
${NFC_HOME}/lib/axis/rtl/sync_reset.v
