
${NFC_HOME}/rtl/NandFlashController_AXIL_Reg.v
${NFC_HOME}/rtl/NandFlashController_Interface_adapter.v
${NFC_HOME}/rtl/NandFlashController_Top_AXI.v
${NFC_HOME}/rtl/NandFlashController_Top.v
${NFC_HOME}/rtl/NFC_Atom_Command_Async.v
${NFC_HOME}/rtl/NFC_Atom_Command_Generator_to_Physical_Mux.v
${NFC_HOME}/rtl/NFC_Atom_Command_Generator_Top.v
${NFC_HOME}/rtl/NFC_Atom_Command_Sync.v
${NFC_HOME}/rtl/NFC_Atom_Datainput_Async.v
${NFC_HOME}/rtl/NFC_Atom_Datainput_Sync.v
${NFC_HOME}/rtl/NFC_Atom_Dataoutput_Async.v
${NFC_HOME}/rtl/NFC_Atom_Dataoutput_Sync.v
${NFC_HOME}/rtl/NFC_Atom_Idle.v
${NFC_HOME}/rtl/NFC_Command_EraseBlock.v
${NFC_HOME}/rtl/NFC_Command_GetFeature.v
${NFC_HOME}/rtl/NFC_Command_Idle.v
${NFC_HOME}/rtl/NFC_Command_Issue_to_Atom_Command_Generator_Mux.v
${NFC_HOME}/rtl/NFC_Command_Issue_Top.v
${NFC_HOME}/rtl/NFC_Command_ProgramPage.v
${NFC_HOME}/rtl/NFC_Command_ReadPage.v
${NFC_HOME}/rtl/NFC_Command_ReadStatus.v
${NFC_HOME}/rtl/NFC_Command_Reset.v
${NFC_HOME}/rtl/NFC_Command_SetFeature.v
${NFC_HOME}/rtl/NFC_Physical_Input.v
${NFC_HOME}/rtl/NFC_Physical_Output.v
${NFC_HOME}/rtl/NFC_Physical_Top.v
${NFC_HOME}/rtl/NFC_Pinpad.v
